### ISSUE TITLE
grpc failed error

### ISSUE THREAD

**Issue by Prithivraj200** [sebastianbaar/cordova-plugin-nativegeocoder#21] opened 2017-12-26 07:41 UTC
I am getting grpc failed error while using **forward geocoder** most of the time. 

     Kindly help to resolve this.

**Comment by sebastianbaar** [comment] 2018-01-07 09:43
hey @Prithivraj200, are you testing the plugin on a real device or on an emulator/genymotion?

**Comment by Prithivraj200** [comment] 2018-01-11 08:29
Hi,
   I am testing on real device.

**Comment by sebastianbaar** [comment] 2018-01-15 08:56
Mh, ok... please give me some more infos about your tooling & setup:
- For which sdk version / api level are you compiling your app?
- What's your device's Android version?
- Which versions of build-tools, platform-tools and sdk tools are you using?
- Are you using Cordova or Ionic (Native)? Which versions?

**Comment by Prithivraj200** [comment] 2018-01-19 12:27
Hi
  
Please find the setup details below:

  android version of my device: 6.0.1
  I am using ionic-native plugin(2.0.2)

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : 6.5.0 

local packages:
    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 25.2.4
    Node              : v9.3.0
    npm               : 5.6.0 
    OS                : Linux 4.4

Environent Variables:
    ANDROID_HOME : /home/emperor/Android/Sdk

Misc:
    backend : legacy

**Comment by sebastianbaar** [comment] 2018-01-23 22:06
That's a tough one... I'm not sure what causes the problem.. please check the following:
- Update your Android SDK tools and try again.
- There are some problems reported regarding Google Play Services - do you use these in your app? If yes: update & test
- Does this problem occur with different search strings? Or is it always the same?

**Comment by Prithivraj200** [comment] 2018-01-29 08:06
-  I have already updated my Android SDK tools and tried again. But still error persists.
      -    I am not using any google play services in my app.
      -    Sometimes it occur and sometimes it works perfect. (with different string).

**Comment by sebastianbaar** [comment] 2018-01-29 08:47
Please give me examples of both strings that work and that do not work. Do you have any example code to reproduce the error?

**Comment by Prithivraj200** [comment] 2018-01-29 11:02
[https://github.com/Prithivraj200/Geocode](url)

I have uploaded my code here. Kindly check.

**Comment by sebastianbaar** [comment] 2018-01-30 07:40
Thank you. I send you a pull request where I added the plugin cordova-plugin-nativegeocoder & tried with some different locations. Everything works fine for me. Please check my pull request and try with your locations.

**Comment by Prithivraj200** [comment] 2018-01-30 09:16
Ya it's working now. Thanks for your help.

**Comment by sebastianbaar** [comment] 2018-01-30 09:22
Perfect! :-)

**Comment by Prithivraj200** [comment] 2018-01-30 12:23
If I use google play services ,then will I get this error?

**Comment by sebastianbaar** [comment] 2018-01-30 15:13
No, this shouldn't be a problem.

**Comment by Prithivraj200** [comment] 2018-01-30 15:33
But like I said earlier, I am getting this error in a few occasions. 

With same string, Chennai, few times I am getting coordinates and few times not.

**Comment by nikhil0606** [comment] 2018-06-21 07:30
i am also getting same problem

**Comment by nikhil0606** [comment] 2018-06-21 07:33
Actually i am developing an application based reverse geo coding and i  am  also getting same problem like grpc failed . can u help me.

**Comment by ManigandanRaamanathan** [comment] 2018-07-01 17:00
I'm facing the same problem. Can you please provide me the solution?

**Comment by sebastianbaar** [comment] 2018-07-02 12:26
Hey guys,
unfortunately, the grpc error is very common using the Geocoder service on Android.

See SO and Google issue tracker links:
- https://stackoverflow.com/questions/47904342/unexpected-grpc-failed-using-geocoder
- https://stackoverflow.com/questions/47019348/android-grpc-failed-on-nexus-5
- https://issuetracker.google.com/issues/64418751

There is no fix for this error as far as I can see. The only thing I could figure out though is that the grpc error is thrown with bad (or no) internet connection. I'm going to check for connectivity before trying to access Geocoder on Android and hope that this will fix the error - at least most of the time... I will let you know as soon as I committed the fix and hope that you can help me test :-)

Cheers

**Comment by rsgilbert** [comment] 2018-07-06 17:07
Same problem here

**Comment by sebastianbaar** [comment] 2018-07-10 09:16
I published a new version 3.1.2.
I now throw an "No Internet Access" error if that's the reason for grpc failing. 

If you __still get an "grpc failed" error__ please comment [here](https://issuetracker.google.com/issues/64418751) (https://issuetracker.google.com/issues/64418751) as this is the most recent issue posted on Google's Issue Tracker! I can not fix this error as it is a problem on Google's site...

Thank you guys for using the plugin and filing the issue. I hope the error is fixed soon! 

Cheers!

**Closed as completed by sebastianbaar** 2018-07-10 09:16 UTC
Labels: bug
