### ISSUE TITLE
missing command error 

### ISSUE THREAD

**Issue by chiranjitkuiry** [sebastianbaar/cordova-plugin-nativegeocoder#36] opened 2018-12-08 15:59 UTC
I use this code but it shows above error 

this.nativeGeocoder.reverseGeocode(this.letitude, this.longitude, options)
      .then((result: NativeGeocoderReverseResult[]) =>{
        console.log(result);
        console.log(JSON.stringify(result[0]));

**Comment by sebastianbaar** [comment] 2018-12-09 08:35
Hey @chiranjitkuiry, 
please fill out the bug template and point out where the error shows up in your code:

Thanks!

--------- 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior or sample code/repo.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Plugin Version**
vX.X.X

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] or Emulator: [e.g. Nexus 7]
 - OS: [e.g. iOS8.1]

**Additional context**
Add any other context about the problem here.

**Comment by chiranjitkuiry** [comment] 2018-12-20 15:06
I am trying to get user location, whenever my app launches in a device.
To do I use the code which is given in

https://ionicframework.com/docs/native/native-geocoder/

It gives me the lat and long in my console, but whenever I use the reverseGeocode function it gives the this error 

![screenshot 13](https://user-images.githubusercontent.com/22238776/50292288-b59bc180-0496-11e9-98b2-497da679812f.png)

I tried this in my real device but the result is the same.

I am using the latest version of ionic 


If u need any information pls let me know , Thank you for your time

**Comment by sebastianbaar** [comment] 2019-02-28 07:52
Hey @chiranjitkuiry,
do you still have this error showing up or can I close the issue? If you still run into the problem please show me the code (with imports etc.) that is causing the error and the error message that is showing up on the device.

**Comment by sebastianbaar** [comment] 2019-04-09 04:27
Closed due to inactivity

**Closed as completed by sebastianbaar** 2019-04-09 04:27 UTC
Labels: bug
