### ISSUE TITLE
Cordova geocoder stops working

### ISSUE THREAD

**Issue by vitor-diniz** [sebastianbaar/cordova-plugin-nativegeocoder#15] opened 2017-10-30 14:37 UTC
I started using cordova geocoder in my project. In my first attempts to use it, it wasn't working, falling into the catch exception. And in a day, out of nothing, it started to work, returning me the adress. And, now, a few days later, it stopped working again. Is there any problem with its service? Because I'm sure I haven't changed my code so it stop working.

**Comment by sebastianbaar** [comment] 2017-11-15 15:09
Hey @vitor-diniz,

I'm sorry, I have no idea what causes this kind of behavior... We would have to debug the native code but unfortunately I cannot reproduce the error. Do you any example code that always behaves like this?

Cheers

**Comment by sebastianbaar** [comment] 2017-11-28 22:35
I did some research and it could be a restriction from Apple:

> After initiating a reverse-geocoding request, do not attempt to initiate another reverse- or forward-geocoding request. Geocoding requests are rate-limited for each app, so making too many requests in a short period of time may cause some of the requests to fail. When the maximum rate is exceeded, the geocoder passes an error object with the value network to your completion handler.
> (https://developer.apple.com/documentation/corelocation/clgeocoder/1423621-reversegeocodelocation)

**Comment by vitor-diniz** [comment] 2017-11-29 09:44
Hey @sebastianbaar, 
Thanks for the answer. It could be something like that, because I'm using both reverse and foward geocode in that part of the application. But I don't think I was able to reach the request limit. Anyway, it looks like that it is working better now. I will try to check and keep my eye on it.

**Comment by sebastianbaar** [comment] 2017-11-29 12:19
Ok nice. I will close this issue for now. Feel free to open it again if you run into the problem again.

Cheers

**Closed as completed by sebastianbaar** 2017-11-29 12:19 UTC
